#!/usr/bin/env bash
# Build index.yaml for GitHub Pages Helm repository. Chart packages stay on GitHub Releases;
# index.yaml references their download URLs.
set -euo pipefail

TAG="${TAG:?Set TAG to the release tag (e.g. v1.0.0)}"
OWNER="${GITHUB_REPOSITORY_OWNER:?}"
REPO="${GITHUB_REPOSITORY#*/}"
VER="${TAG#v}"
CHART_FILE="intune2snipe-${VER}.tgz"
BASE_URL="https://github.com/${OWNER}/${REPO}/releases/download/${TAG}/"
OUT_DIR="${GITHUB_WORKSPACE:?}/helm-chart-repo"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

git fetch origin gh-pages:gh-pages 2>/dev/null || true
MERGE_FILE=""
if git show gh-pages:index.yaml >"${TMP}/previous-index.yaml" 2>/dev/null; then
  MERGE_FILE="${TMP}/previous-index.yaml"
  echo "Found existing index on gh-pages; will merge"
fi

WORKDIR="${TMP}/charts"
mkdir -p "$WORKDIR"
cd "$WORKDIR"

echo "Downloading ${CHART_FILE} from release ${TAG}..."
for i in 1 2 3 4 5; do
  if curl -fsSL -o "$CHART_FILE" "${BASE_URL}${CHART_FILE}"; then
    break
  fi
  echo "Retry $i..."
  sleep 3
done

if [[ ! -f "$CHART_FILE" ]]; then
  echo "Failed to download chart package from ${BASE_URL}${CHART_FILE}"
  exit 1
fi

if [[ -n "$MERGE_FILE" ]]; then
  helm repo index . --url "${BASE_URL}" --merge "$MERGE_FILE"
else
  echo "Creating initial Helm repo index"
  helm repo index . --url "${BASE_URL}"
fi

mkdir -p "$OUT_DIR"
cp index.yaml "$OUT_DIR/index.yaml"

cat >"$OUT_DIR/README.md" <<EOF
# Intune2snipe Helm chart repository

This branch is **generated by CI** when a release is published. Do not edit by hand.

Add the repository:

\`\`\`bash
helm repo add intune2snipe https://${OWNER}.github.io/${REPO}/
helm repo update
helm search repo intune2snipe --versions
\`\`\`

Install (pick a version from \`helm search\`):

\`\`\`bash
helm upgrade --install intune2snipe intune2snipe/intune2snipe --version ${VER} \\
  --namespace intune2snipe --create-namespace
\`\`\`

See [Kubernetes deployment](https://github.com/${OWNER}/${REPO}/blob/main/docs/deployment-kubernetes.md).
EOF

echo "Wrote ${OUT_DIR}/index.yaml"
